# Generated by Django 3.0.5 on 2020-04-07 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200407_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='admin_note',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='patient',
            name='admin_note',
            field=models.CharField(default='', max_length=255),
        ),
    ]
