# Generated by Django 3.0.5 on 2020-04-08 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200407_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_avaliability',
            name='day_in_week',
            field=models.CharField(max_length=10),
        ),
    ]
