# Generated by Django 3.0.5 on 2020-04-24 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200423_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.CharField(max_length=22)),
                ('type_idx', models.CharField(max_length=22)),
                ('type_name', models.CharField(max_length=50)),
                ('state_idx', models.CharField(max_length=22)),
                ('state_name', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10)),
                ('created_on', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.Payment'),
            preserve_default=False,
        ),
    ]
